Allow compilation on Clang
Clang seems to be more strict in terms of casting. The `file_type` enum, which is pushed via `GINT_TO_POINTER` macro, needs to be casted on the other way around when popping (`GPOINTER_TO_INT`), otherwise the following error is raised on compilation:

    src/myloader_stream.c:213:8: error: cast to smaller integer type 'enum file_type' from 'gpointer' (aka 'void *') [-Werror,-Wvoid-pointer-to-enum-cast]
        ft=(enum file_type)g_async_queue_pop(stream_queue);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tested on Clang 13.0.1 on Linux, via multithreaded streaming dump+restore.

See https://developer.gimp.org/api/2.0/glib/glib-Type-Conversion-Macros.html for the Glib macros reference.