Fix building on musl libc
On musl libc we are getting buid errors:
mydumper/src/mydumper_stream.c:100:9: error: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-
function-declaration]
  100 |       f=open(sf->filename,O_RDONLY);
      |         ^~~~
      |         popen
mydumper/src/mydumper_stream.c:100:27: error: 'O_RDONLY' undeclared (first use in this function)
  100 |       f=open(sf->filename,O_RDONLY);
      |                           ^~~~~~~~
This probably due to musl being more strict. Fix was to include the
fcntl.h header file as the Linux Manual Page suggests open should come
from fcntl.h

First reported on Gentoo Linux with musl profile

Bug: https://bugs.gentoo.org/935389
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>